### ISSUE TITLE
Combined data sending

### ISSUE THREAD

**Issue by BurakOgutken** [cabbi/modbus_client_serial#8]
Hello, I shared the code below, when I use it this way, I get an error, how can I send it?

```
var metaRequest = ModbusUint16Register(
      name: "SetMetaBauer",
      type: ModbusElementType.holdingRegister,
      address: 40280,
      onUpdate: (self) {
        if (kDebugMode) {
          print(self.value);
        }
      });

Future<void> setMetaBauer() async {
    var meta1 = Zeus().extendTo70Bytes("contract-id: rfid: burak");
    var meta2 = Zeus().extendTo50Bytes("evse-id: DE*BDO*E8025334492*1");
    var combinedMeta = Uint8List(meta1.length + meta2.length);
    combinedMeta.setRange(0, meta1.length, meta1);
    combinedMeta.setRange(meta1.length, meta1.length + meta2.length, meta2);

    String hexString = Zeus().toHexString(combinedMeta);

    var req = metaRequest.getWriteRequest(hexString,
        unitId: 1, rawValue: false);
    var result = await _modbusClient.send(req);
    if (kDebugMode) {
      print(result);
    }
  }
```

```
E/flutter (27779): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method '-'.
E/flutter (27779): Receiver: "636f6e74726163742d69643a20726669643a20627572616b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000657673652d69643a2044452a42444f2a45383032353333343439322a31000000000000000000000000000000000000000000"
```

**Comment by cabbi** [comment]
Can you please explain:
- what is the main goal
- what type of element is "metaRequest"
- what is the error you get

**Comment by BurakOgutken** [comment]
We want to write variable size array to modbus addresses as uint8, string etc.
Sorry, I forgot to send that batch, I updated it.

**Comment by BurakOgutken** [comment]
Do you have any ideas on how we can do this?

**Comment by cabbi** [comment]
I think you might use file records https://pub.dev/packages/modbus_client#modbus-file-records-a-idfilerecordsa

But it is not really clear to me what kind of device you are connected to. What are the device (i.e. Modbus Server) specs? Which kind of register is this device using?

**Comment by BurakOgutken** [comment]
energy meter we are trying to connect we must send some meta data to device

**Comment by BurakOgutken** [comment]
we are trying send this data to device

`01 10 9D 57 00 78 F0 63 6F 6E 74 72 61 63 74 2D 69 64 3A 20 72 66 69 64 3A 31 32 33 34 35 36 37 38 61 62 63 64 65 66 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 65 76 73 65 2D 69 64 3A 20 44 45 2A 42 44 4F 2A 45 38 30 32 35 33 33 34 34 39 32 2A 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 19 5C`

**Comment by cabbi** [comment]
Ok, and what is device spec saying about those meta data, are those stored into registries or file records? Which is the requested write function code?

**Comment by BurakOgutken** [comment]
device keeping this holding registers

```
Future<void> setMetaBauer() async {
  var metaRequest = ModbusUint16Register(
      name: "SetMetaBauer",
      type: ModbusElementType.holdingRegister,
      address: 40280,
      onUpdate: (self) {
        if (kDebugMode) {
          print(self.value);
        }
      });

 var hexs =
        "01 10 9D 57 00 78 F0 63 6F 6E 74 72 61 63 74 2D 69 64 3A 20 72 66 69 64 3A 31 32 33 34 35 36 37 38 61 62 63 64 65 66 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 65 76 73 65 2D 69 64 3A 20 44 45 2A 42 44 4F 2A 45 38 30 32 35 33 33 34 34 39 32 2A 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2B 04";

    var dataToSend = Zeus().hexStringToBytes(hexs.replaceAll(' ', ''));
  
    var req = metaRequest.getWriteRequest(dataToSend, unitId: 1);
    var result = await _modbusClient.send(req);
    if (kDebugMode) {
      print(result);
    }
 }
```


error is 
```

: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'List<int>' has no instance method '-'.
E/flutter ( 7090): Receiver: Instance(length:249) of '_GrowableList'
E/flutter ( 7090): Tried calling: -(0.0)
```

**Comment by cabbi** [comment]
Ok, now it's clear to me

Actually modbus_client package does not support writing multiple registers at once. That said you need to perform a loop by sending one by one Uint6 requests (i.e. send 2 bytes of the meta data for each request)  incrementing the address of the request at each iteration

**Comment by BurakOgutken** [comment]
hi again,

I tried to change your library, but it seemed too complicated for me. Is it possible to add this feature to your library?
The energy meter I use does not allow me to send it separately.

**Comment by cabbi** [comment]
I'm the way implementing a `ModbusBytesRegister` class that handles bytes array but I've a few questions for you.

- What kind of register are those, holding registers? 
- If not, what is the required write function code?
 
I'm asking because I see the bytes array you want to write has an odd length (249 bytes) which is strange because Modbus registers are 16 bits long so I'm expecting an event length array.

**Comment by cabbi** [comment]
In this branch (https://github.com/cabbi/modbus_client/tree/ModbusBytesRegister) you will find an example of reading and writing bytes array. As I already told you, bytes array length must be even.
Please let me know if this new register element fits your needs

**Comment by BurakOgutken** [comment]
thank you so much its worked

**Comment by cabbi** [comment]
New modbus_client version 1.2.1 has been released
